# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bde3dcd3ca8fd789d5ee884c6ea927fc917d537a479499d5aa9a20b5bd6f1545b0e41d5d005c00254990f1b25f178dd93c4921b0779c7de0dc7c0733a1c7565d

test:
  secret_key_base: 6a6017dbabb45da7fadc5e1dbc8e3228d8267e520dfe99350443f179f984fa902bfa77aeb8cdaa2bd97cb9e181d393725eecf0ce66651a250c9659d98d310f4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
